### ISSUE TITLE
Exploratory Boxplots 

### ISSUE THREAD

**Issue by mariam16548** [PriceLab/chip-seq-motif-study#11]
@paul-shannon So I've pushed the boxplots onto github, so they should be found here: 

explore/ctcf/Boxplot CTCF motif scores.png
explore/ctcf/CTCF phast scores.png
explore/ctcf/CTCF comparison of 3 boxplots.png

Some insights from these boxplots: 
- Phast7 and phast100 have similar spread in the data (same minimum values), but the phast100 data values are more compressed and it has a lower third quartile, maximum value, and median (same as its minimum). Phast100 data values have some outliers that fall within the phast7 data ranges. Phast7 has fewer outliers, but it also has more spread in its data values.  
- I decided to upload phast 7 and phast100 separate from the motif score boxplot (as well as upload  comparison of all three together) since because their data value ranges were much more different and it allowed for me to compare more easily between phast7 and phast100. 
- From the motif score boxplot, I can see that it has the widest range between all three boxplots. It had the fewest number of outliers as well as the highest maximum, median, first/third quartiles, as well as the lowest minimum between all of the boxplots.

**Comment by paul-shannon** [comment]
@mariam16548 Can you check-in the full data.frame for CTCF?  With ChIP-seq scores, motif scores, phast7 and phast100?

**Comment by mariam16548** [comment]
@paul-shannon I just checked it in! Please let me know if you have any issues with it!
bulk/chr19-demo/ctcf.csv
