### ISSUE TITLE
ChIP-seq peak notes 

### ISSUE THREAD

**Issue by mariam16548** [PriceLab/chip-seq-motif-study#5]
My notes for the first paper: 
- Peak calling with ChIP-seq data comes with an issue of identifying candidate peaks (which ones denote a tf binding sites vs. those that are "experimental noise", or something else)
- In order to combat this problem, they surveyed 30 different methods to see which was best. 
- They found that peak detection was reduced when ChIP and input signals are explicitly combined. (Even after doing extra research on it, I'm still not sure what this exactly means)
- For statistical significance, they found methods using a Poisson test to rank the peaks, is more powerful than the Binomial test. 
- Also, using windows of different sizes to scan the genome for potential peaks is more powerful than not using different sizes. 

Notes for the more recent paper (Grytten): 
- The developed a tool called "Graph Peak Caller" based on MACS2
- They used A. thaliana to conduct the study, showing that the peaks found by Graph Peak Caller, in general, are "more enriched for DNA-binding motifs than those found by MACS2 on a linear reference genome". 

Here is the source for the paper I was looking over (published in May 2016, appeared in the journal in May 2017): [https://doi.org/10.1093/bib/bbw035](url)
Reuben Thomas, Sean Thomas, Alisha K Holloway, Katherine S Pollard, Features that define the best ChIP-seq peak calling algorithms, Briefings in Bioinformatics, Volume 18, Issue 3, May 2017, Pages 441–450, https://doi.org/10.1093/bib/bbw035

The other one I spoke to you about (published in February of 2019): [https://doi.org/10.1371/journal.pcbi.1006731](url)
Grytten I, Rand KD, Nederbragt AJ, Storvik GO, Glad IK, Sandve GK (2019) Graph Peak Caller: Calling ChIP-seq peaks on graph-based reference genomes. PLoS Comput Biol 15(2): e1006731. https://doi.org/10.1371/journal.pcbi.1006731

**Comment by paul-shannon** [comment]
Very helpful, Mariam - thanks!

With this information archived on github, please set this question aside until I hear back from our colleagues.

Please move on to understand

  - default function arguments (aka, default parameters)
  - using the function is.na(arg) to test for their presence
  - write some exploratory code, a function that does something trivial (like uppercase a string)
    using a default argument.  you can call the function in two ways: using the default, overriding the default

       uppercaseString <- function(targetString=NA)){
          if(is.na(targetString))
             return(“THIS IS A DEFAULT STRING”)
           return(topper(targetString)


Not a very useful function.   But it demonstrates the use of defaults and testing for NA
