### ISSUE TITLE
sliceBamFile function

### ISSUE THREAD

**Issue by mariam16548** [PriceLab/chip-seq-motif-study#9]
I've put the function into the ctcf folder (sliceBamFunction.R).

**Comment by mariam16548** [comment]
@paul-shannon

**Comment by paul-shannon** [comment]
@mariam16548 I am creating a new file ````sliceBamFile.R```` based on your function.  It will have all of my suggestions, some of which are substantial, some just stylistic.   Your code is headed in the right direction!

**Comment by paul-shannon** [comment]
@mariam16548 
see ````~/github/chip-seq-motif-study/explore/ctcf/sliceBamFile.R````
Note that this can be run and tested from the shell:
````
bash> R -f sliceBamFile.R
--- test_sliceBamFile
[1] TRUE
````
Lots of stylistic and substantial modifications here.   Please absorb them!

**Comment by paul-shannon** [comment]
@mariam16548 
Next task:
I suggest a more friendly signature of sliceBamFile:
````
sliceBamFile <- function(bamFile,  newBamFileName, chrom, start=NA, end=NA)
````
If you call this function without a start and end, it implies "give me the whole chromosome".  In that case, start <-1, and end can be looked up this way:
````
library(org.Hs.eg.db)
org.Hs.egCHRLENGTHS[[19]]    #  80373285
````
This is friendly in that it saves the caller the task of looking up the end of the chromosome of interest in those cases where we want an entire chromosome from the bam file.

**Comment by mariam16548** [comment]
@paul-shannon 
I've made these requested changes and put them in sliceBamFunction.R. I will continue to look through your suggestions to make sure I understand them!

**Comment by mariam16548** [comment]
Thank you for the feedback (I went back in and applied the suggestions)!
-Mariam
